### ISSUE TITLE
typo in name of dpkg.list file (dpkg.lst)

### ISSUE THREAD

**Issue by anonymouse64** [mvo5/core-patcher#1]
See:

https://github.com/mvo5/core-patcher/blob/20341f76a1e9b1b8eadcf7fabcacf0f9362eac1e/core-patcher.sh#L23-L26

and where we generate this file: 

https://github.com/snapcore/core/blob/18c4899e5866e56eee014b437c7cb5f6f346eb13/live-build/hooks/600-no-debian.binary#L11-L12

**Comment by mvo5** [comment]
This is fixed now.
